title: 小像素点
description: 猫不喝咖啡 所以这里没有咖啡 也没有猫
keywords: 异梦系列,猫球博客
favicon: favicon.ico

mq: https://limaoqiu.com
mq_d: 
mq_i: /i
jquery: https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js

mq_url: https://像素点.cn